# Generated by Django 4.0.6 on 2022-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feels', '0007_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
