# Generated by Django 4.0.6 on 2022-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feels', '0010_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
