# Generated by Django 4.0.6 on 2022-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feels", "0008_alter_user_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="music",
            name="album",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="music",
            name="genre",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="music",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=255),
        ),
    ]
