# Generated by Django 4.0.6 on 2022-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feels", "0012_user_gender_alter_movie_genre_alter_movie_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Default"),
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Rather Not specify"),
                ],
                default=0,
            ),
        ),
    ]
