# Generated by Django 4.0.6 on 2022-11-07 10:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("feels", "0015_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
