# Generated by Django 4.0.6 on 2022-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feels", "0016_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "Default"), (1, "Male"), (2, "Female")]
            ),
        ),
    ]
